/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj;

import java.awt.Color;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Random;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;






/**
 *
 * @author User
 */
public class Admin_Program extends javax.swing.JFrame {
    User user = new User();
    Admin currentAdmin = new Admin();
    ArrayList<JLabel> errorLabels= new ArrayList<>();
    DefaultTableModel userInfo;
    String allChars[] = {
            // Numbers
            "0", "1", "2", "3", "4", "5", "6", "7", "8", "9",
            // Uppercase alphabets
            "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M",
            "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z",
            // Lowercase alphabets
            "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m",
            "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
            // Common symbols
            "!", "@", "#", "$", "%", "^", "&", "*","?","/"
        };
    Random generator = new Random();
    String password;
    /**
     * Creates new form RegisterUI
     */
    DecimalFormat id = new DecimalFormat("000"); 

    
    public Admin_Program(Admin temp) {
        initComponents();
        ClearErrors();     
        
        userInfo = (DefaultTableModel)jTable1.getModel();   
        
        
        currentAdmin = temp; // current object of user
        currentAdmin.readLoginCredentials();
        
        // need to get all current object user and save it in labels
        currentAdmin.DisplayProfile(ProfileUserType, ProfileID, ProfileFN, ProfileLN, ProfileGender, ProfileEmail, ProfileContact);               
        Admin_ID.setText(currentAdmin.getUserID());
        welcomeMessage.setText("Welcome, "+currentAdmin.getFirstName()+ " " + currentAdmin.getLastName() + " !!");
        
        

        
        
        this.setVisible(true);
        
        

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        RegisterGender = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        RegisterUID = new javax.swing.JTextField();
        RegisterType = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        RegisterFN = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        RegisterLN = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        RegisterMale = new javax.swing.JRadioButton();
        RegisterFemale = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RegisterEmail = new javax.swing.JTextField();
        RegisterContact = new javax.swing.JTextField();
        RegisterButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        RegisterError = new javax.swing.JLabel();
        FNError = new javax.swing.JLabel();
        LNError = new javax.swing.JLabel();
        GenderError = new javax.swing.JLabel();
        EmailError = new javax.swing.JLabel();
        ContactError = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        SelectUserType = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        infoFN = new javax.swing.JTextField();
        infoLN = new javax.swing.JTextField();
        infoGender = new javax.swing.JTextField();
        infoEmail = new javax.swing.JTextField();
        infoContact = new javax.swing.JTextField();
        infoPassword = new javax.swing.JTextField();
        infoDelete = new javax.swing.JButton();
        infoSave = new javax.swing.JButton();
        infoEdit = new javax.swing.JToggleButton();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        SelectUserID = new javax.swing.JComboBox<>();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        FM = new javax.swing.JButton();
        SM = new javax.swing.JButton();
        PM = new javax.swing.JButton();
        IM = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        ProfileID = new javax.swing.JLabel();
        ProfileUserType = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        ProfileFN = new javax.swing.JLabel();
        ProfileLN = new javax.swing.JLabel();
        ProfileGender = new javax.swing.JLabel();
        ProfileEmail = new javax.swing.JLabel();
        ProfileContact = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        ProfileCurrentPass = new javax.swing.JPasswordField();
        ProfileNewPass = new javax.swing.JPasswordField();
        ProfileChgPass = new javax.swing.JButton();
        ChgPassError = new javax.swing.JLabel();
        ShowHidePass = new javax.swing.JToggleButton();
        btnLogout = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        welcomeMessage = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        Admin_ID = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin");
        setPreferredSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        getContentPane().setLayout(null);

        jTabbedPane1.setBackground(new java.awt.Color(228, 224, 225));
        jTabbedPane1.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N

        jPanel4.setLayout(null);

        jPanel1.setBackground(new java.awt.Color(73, 54, 40));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(171, 136, 109));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Register Users");

        RegisterUID.setEditable(false);
        RegisterUID.setBackground(new java.awt.Color(179, 164, 155));
        RegisterUID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterUID.setForeground(new java.awt.Color(83, 60, 43));
        RegisterUID.setToolTipText("Choose User Type first.");
        RegisterUID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        RegisterUID.setFocusable(false);
        RegisterUID.setSelectionColor(new java.awt.Color(178, 152, 132));
        RegisterUID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterUIDActionPerformed(evt);
            }
        });

        RegisterType.setBackground(new java.awt.Color(214, 192, 179));
        RegisterType.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        RegisterType.setForeground(new java.awt.Color(83, 60, 43));
        RegisterType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Sales Manager (SM)", "Purchase Manager (PM)", "Inventory Manager (IM)", "Finance Manager (FM)" }));
        RegisterType.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        RegisterType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        RegisterType.setFocusable(false);
        RegisterType.setOpaque(true);
        RegisterType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterTypeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 136, 109));
        jLabel3.setText("User Type   ");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(171, 136, 109));
        jLabel4.setText("User ID               ");

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(171, 136, 109));
        jLabel5.setText("First Name");

        RegisterFN.setBackground(new java.awt.Color(214, 192, 179));
        RegisterFN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterFN.setForeground(new java.awt.Color(83, 60, 43));
        RegisterFN.setToolTipText("First Name");
        RegisterFN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        RegisterFN.setSelectionColor(new java.awt.Color(178, 152, 132));
        RegisterFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterFNActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(171, 136, 109));
        jLabel6.setText("Last Name");

        RegisterLN.setBackground(new java.awt.Color(214, 192, 179));
        RegisterLN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterLN.setForeground(new java.awt.Color(83, 60, 43));
        RegisterLN.setToolTipText("Last Name");
        RegisterLN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        RegisterLN.setSelectionColor(new java.awt.Color(178, 152, 132));
        RegisterLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterLNActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(171, 136, 109));
        jLabel7.setText("Gender");

        RegisterMale.setBackground(new java.awt.Color(73, 54, 40));
        RegisterGender.add(RegisterMale);
        RegisterMale.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RegisterMale.setForeground(new java.awt.Color(171, 136, 109));
        RegisterMale.setText(" Male");
        RegisterMale.setBorder(null);
        RegisterMale.setContentAreaFilled(false);
        RegisterMale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterMale.setFocusable(false);
        RegisterMale.setOpaque(true);
        RegisterMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterMaleActionPerformed(evt);
            }
        });

        RegisterFemale.setBackground(new java.awt.Color(73, 54, 40));
        RegisterGender.add(RegisterFemale);
        RegisterFemale.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        RegisterFemale.setForeground(new java.awt.Color(171, 136, 109));
        RegisterFemale.setText(" Female");
        RegisterFemale.setBorder(null);
        RegisterFemale.setContentAreaFilled(false);
        RegisterFemale.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RegisterFemale.setFocusable(false);
        RegisterFemale.setOpaque(true);
        RegisterFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterFemaleActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(171, 136, 109));
        jLabel8.setText("Email");

        jLabel9.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(171, 136, 109));
        jLabel9.setText("Contact No.");

        RegisterEmail.setBackground(new java.awt.Color(214, 192, 179));
        RegisterEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterEmail.setForeground(new java.awt.Color(83, 60, 43));
        RegisterEmail.setToolTipText("Email must include \"@\"");
        RegisterEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        RegisterEmail.setSelectionColor(new java.awt.Color(178, 152, 132));
        RegisterEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterEmailActionPerformed(evt);
            }
        });

        RegisterContact.setBackground(new java.awt.Color(214, 192, 179));
        RegisterContact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        RegisterContact.setForeground(new java.awt.Color(83, 60, 43));
        RegisterContact.setToolTipText("Contact No. should be all numeric");
        RegisterContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        RegisterContact.setSelectionColor(new java.awt.Color(178, 152, 132));
        RegisterContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterContactActionPerformed(evt);
            }
        });

        RegisterButton.setBackground(new java.awt.Color(178, 152, 132));
        RegisterButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        RegisterButton.setForeground(new java.awt.Color(46, 36, 28));
        RegisterButton.setText("Register");
        RegisterButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        RegisterButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        jSeparator2.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator2.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator3.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel10.setFont(new java.awt.Font("Yu Gothic UI", 0, 10)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(171, 136, 109));
        jLabel10.setText("*passwords will be sent through email upon registration");

        RegisterError.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        RegisterError.setForeground(new java.awt.Color(255, 0, 51));
        RegisterError.setText("Make sure all fields are filled accordingly");

        FNError.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        FNError.setForeground(new java.awt.Color(255, 0, 51));
        FNError.setText("!");

        LNError.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        LNError.setForeground(new java.awt.Color(255, 0, 51));
        LNError.setText("!");

        GenderError.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        GenderError.setForeground(new java.awt.Color(255, 0, 51));
        GenderError.setText("!");

        EmailError.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        EmailError.setForeground(new java.awt.Color(255, 0, 51));
        EmailError.setText("!");

        ContactError.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        ContactError.setForeground(new java.awt.Color(255, 0, 51));
        ContactError.setText("!");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(RegisterLN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterType, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterUID, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterFN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(RegisterMale)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RegisterFemale)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FNError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(LNError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(GenderError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(RegisterError, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(RegisterContact, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(RegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(EmailError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContactError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(RegisterType, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(RegisterEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmailError))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RegisterUID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(RegisterContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ContactError))
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RegisterFN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(FNError))
                            .addComponent(jLabel5))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(RegisterLN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(LNError)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(RegisterMale)
                            .addComponent(RegisterFemale)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(GenderError))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(RegisterError))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jPanel4.add(jPanel1);
        jPanel1.setBounds(270, 35, 780, 410);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jLabel12.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel12.setPreferredSize(new java.awt.Dimension(1280, 720));
        jPanel4.add(jLabel12);
        jLabel12.setBounds(0, -157, 1280, 730);

        jTabbedPane1.addTab("Register Users", jPanel4);

        jPanel7.setBackground(new java.awt.Color(214, 192, 179));
        jPanel7.setLayout(null);

        jPanel9.setBackground(new java.awt.Color(73, 54, 40));

        jTable1.setBackground(new java.awt.Color(214, 192, 179));
        jTable1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(73, 54, 40));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Type", "User ID", "First Name", "Last Name", "Gender", "Email", "Contact No.", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable1MousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(15);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(50);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(10);
            jTable1.getColumnModel().getColumn(7).setPreferredWidth(45);
        }

        SelectUserType.setBackground(new java.awt.Color(214, 192, 179));
        SelectUserType.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        SelectUserType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "A", "PM", "IM", "FM", "SM" }));
        SelectUserType.setSelectedItem("");
        SelectUserType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectUserTypeActionPerformed(evt);
            }
        });

        jLabel25.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(171, 136, 109));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setText("User Information");

        jLabel26.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(171, 136, 109));
        jLabel26.setText("A - Admin   SM - Sales Manager   IM - Inventory Manager   FM - Finance Manager   PM - Purchase Manager");

        jLabel27.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(171, 136, 109));
        jLabel27.setText("User Type   ");

        infoFN.setEditable(false);
        infoFN.setBackground(new java.awt.Color(179, 164, 155));
        infoFN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoFN.setForeground(new java.awt.Color(83, 60, 43));
        infoFN.setToolTipText("First Name");
        infoFN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        infoFN.setSelectionColor(new java.awt.Color(178, 152, 132));
        infoFN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoFNActionPerformed(evt);
            }
        });

        infoLN.setEditable(false);
        infoLN.setBackground(new java.awt.Color(179, 164, 155));
        infoLN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoLN.setForeground(new java.awt.Color(83, 60, 43));
        infoLN.setToolTipText("Last Name");
        infoLN.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        infoLN.setSelectionColor(new java.awt.Color(178, 152, 132));
        infoLN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoLNActionPerformed(evt);
            }
        });

        infoGender.setEditable(false);
        infoGender.setBackground(new java.awt.Color(179, 164, 155));
        infoGender.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoGender.setForeground(new java.awt.Color(83, 60, 43));
        infoGender.setToolTipText("Gender");
        infoGender.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        infoGender.setSelectionColor(new java.awt.Color(178, 152, 132));
        infoGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoGenderActionPerformed(evt);
            }
        });

        infoEmail.setEditable(false);
        infoEmail.setBackground(new java.awt.Color(179, 164, 155));
        infoEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoEmail.setForeground(new java.awt.Color(83, 60, 43));
        infoEmail.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        infoEmail.setToolTipText("Email must include '@'");
        infoEmail.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        infoEmail.setSelectionColor(new java.awt.Color(178, 152, 132));
        infoEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEmailActionPerformed(evt);
            }
        });

        infoContact.setEditable(false);
        infoContact.setBackground(new java.awt.Color(179, 164, 155));
        infoContact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoContact.setForeground(new java.awt.Color(83, 60, 43));
        infoContact.setToolTipText("Contact number should be all numeric");
        infoContact.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        infoContact.setSelectionColor(new java.awt.Color(178, 152, 132));
        infoContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoContactActionPerformed(evt);
            }
        });

        infoPassword.setEditable(false);
        infoPassword.setBackground(new java.awt.Color(179, 164, 155));
        infoPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        infoPassword.setForeground(new java.awt.Color(83, 60, 43));
        infoPassword.setToolTipText("Password must be more than 8 letters");
        infoPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        infoPassword.setSelectionColor(new java.awt.Color(178, 152, 132));
        infoPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoPasswordActionPerformed(evt);
            }
        });

        infoDelete.setBackground(new java.awt.Color(178, 152, 132));
        infoDelete.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        infoDelete.setForeground(new java.awt.Color(46, 36, 28));
        infoDelete.setText("Delete");
        infoDelete.setEnabled(false);
        infoDelete.setFocusable(false);
        infoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoDeleteActionPerformed(evt);
            }
        });

        infoSave.setBackground(new java.awt.Color(178, 152, 132));
        infoSave.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        infoSave.setForeground(new java.awt.Color(46, 36, 28));
        infoSave.setText("Save");
        infoSave.setEnabled(false);
        infoSave.setFocusable(false);
        infoSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoSaveActionPerformed(evt);
            }
        });

        infoEdit.setBackground(new java.awt.Color(178, 152, 132));
        infoEdit.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        infoEdit.setForeground(new java.awt.Color(46, 36, 28));
        infoEdit.setText("Edit");
        infoEdit.setFocusable(false);
        infoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                infoEditActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(171, 136, 109));
        jLabel28.setText("First Name");

        jLabel29.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(171, 136, 109));
        jLabel29.setText("Last Name");

        jLabel30.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(171, 136, 109));
        jLabel30.setText("Gender");

        jLabel31.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(171, 136, 109));
        jLabel31.setText("Email");

        jLabel32.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(171, 136, 109));
        jLabel32.setText("Contact No.");

        jLabel33.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(171, 136, 109));
        jLabel33.setText("Password");

        jLabel34.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(171, 136, 109));
        jLabel34.setText("User ID");

        SelectUserID.setBackground(new java.awt.Color(214, 192, 179));
        SelectUserID.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        SelectUserID.setSelectedItem("");
        SelectUserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectUserIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SelectUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 796, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SelectUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoFN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel30)
                                    .addComponent(infoGender, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel32)
                                    .addComponent(infoContact, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(infoLN, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(infoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel31)
                                    .addComponent(infoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(26, 26, 26))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                        .addComponent(infoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(infoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(infoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel34)
                    .addComponent(SelectUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel28)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(infoFN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel29)
                                .addGap(4, 4, 4)
                                .addComponent(infoLN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31))
                        .addGap(5, 5, 5)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoGender, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoContact, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(infoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(infoSave, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36))))
        );

        jPanel7.add(jPanel9);
        jPanel9.setBounds(20, 28, 1230, 420);

        jTabbedPane1.addTab("Modify Users", jPanel7);

        jPanel10.setBackground(new java.awt.Color(214, 192, 179));
        jPanel10.setLayout(null);

        jPanel11.setBackground(new java.awt.Color(73, 54, 40));

        jLabel35.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(171, 136, 109));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel35.setText("Choose the role:");

        jSeparator5.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator5.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator6.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator6.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        FM.setBackground(new java.awt.Color(73, 54, 40));
        FM.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        FM.setForeground(new java.awt.Color(171, 136, 109));
        FM.setText("Finance Manager");
        FM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 136, 109), 3));
        FM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        FM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FMActionPerformed(evt);
            }
        });

        SM.setBackground(new java.awt.Color(73, 54, 40));
        SM.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        SM.setForeground(new java.awt.Color(171, 136, 109));
        SM.setText("Sales Manager");
        SM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 136, 109), 3));
        SM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SMActionPerformed(evt);
            }
        });

        PM.setBackground(new java.awt.Color(73, 54, 40));
        PM.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        PM.setForeground(new java.awt.Color(171, 136, 109));
        PM.setText("Purchase Manager");
        PM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 136, 109), 3));
        PM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PMActionPerformed(evt);
            }
        });

        IM.setBackground(new java.awt.Color(73, 54, 40));
        IM.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        IM.setForeground(new java.awt.Color(171, 136, 109));
        IM.setText("Inventory Manager");
        IM.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(171, 136, 109), 3));
        IM.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        IM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IMActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(FM, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SM, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(144, 144, 144)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(217, 217, 217))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(SM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(IM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(FM, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jPanel10.add(jPanel11);
        jPanel11.setBounds(20, 28, 1230, 420);

        jTabbedPane1.addTab("Extra Functions", jPanel10);

        jPanel3.setBackground(new java.awt.Color(214, 192, 179));
        jPanel3.setLayout(null);

        jPanel8.setBackground(new java.awt.Color(73, 54, 40));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel21.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(171, 136, 109));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Profile");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/profile-modified (1).png"))); // NOI18N

        ProfileID.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        ProfileID.setForeground(new java.awt.Color(171, 136, 109));
        ProfileID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileID.setText("Profile ID");

        ProfileUserType.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        ProfileUserType.setForeground(new java.awt.Color(171, 136, 109));
        ProfileUserType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProfileUserType.setText("Profile Type");

        jSeparator1.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator1.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(171, 136, 109));
        jLabel16.setText("First Name");

        jLabel17.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(171, 136, 109));
        jLabel17.setText("Last Name");

        jLabel18.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(171, 136, 109));
        jLabel18.setText("Gender");

        jLabel20.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(171, 136, 109));
        jLabel20.setText("Contact No.");

        jLabel19.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(171, 136, 109));
        jLabel19.setText("Email");

        jSeparator4.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator4.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator4.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        ProfileFN.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ProfileFN.setForeground(new java.awt.Color(214, 192, 179));
        ProfileFN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ProfileFN.setText("First Name");

        ProfileLN.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ProfileLN.setForeground(new java.awt.Color(214, 192, 179));
        ProfileLN.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ProfileLN.setText("Last Name");

        ProfileGender.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ProfileGender.setForeground(new java.awt.Color(214, 192, 179));
        ProfileGender.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ProfileGender.setText("Gender");

        ProfileEmail.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ProfileEmail.setForeground(new java.awt.Color(214, 192, 179));
        ProfileEmail.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ProfileEmail.setText("Email");

        ProfileContact.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        ProfileContact.setForeground(new java.awt.Color(214, 192, 179));
        ProfileContact.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        ProfileContact.setText("Contact No.");

        jLabel13.setFont(new java.awt.Font("Yu Gothic UI", 0, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(171, 136, 109));
        jLabel13.setText("*Contact the administrator to change personal details");

        jLabel15.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(171, 136, 109));
        jLabel15.setText("Change Password");

        jLabel22.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(171, 136, 109));
        jLabel22.setText("Current Password");

        jLabel24.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(171, 136, 109));
        jLabel24.setText("New Password");

        ProfileCurrentPass.setBackground(new java.awt.Color(214, 192, 179));
        ProfileCurrentPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProfileCurrentPass.setForeground(new java.awt.Color(83, 60, 43));
        ProfileCurrentPass.setToolTipText("Password");
        ProfileCurrentPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        ProfileCurrentPass.setMinimumSize(new java.awt.Dimension(64, 26));
        ProfileCurrentPass.setPreferredSize(new java.awt.Dimension(64, 26));
        ProfileCurrentPass.setSelectionColor(new java.awt.Color(178, 152, 132));

        ProfileNewPass.setBackground(new java.awt.Color(214, 192, 179));
        ProfileNewPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ProfileNewPass.setForeground(new java.awt.Color(83, 60, 43));
        ProfileNewPass.setToolTipText("Password");
        ProfileNewPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        ProfileNewPass.setMinimumSize(new java.awt.Dimension(64, 26));
        ProfileNewPass.setPreferredSize(new java.awt.Dimension(64, 26));
        ProfileNewPass.setSelectionColor(new java.awt.Color(178, 152, 132));

        ProfileChgPass.setBackground(new java.awt.Color(178, 152, 132));
        ProfileChgPass.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        ProfileChgPass.setForeground(new java.awt.Color(46, 36, 28));
        ProfileChgPass.setText("Reset Password");
        ProfileChgPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        ProfileChgPass.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ProfileChgPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfileChgPassActionPerformed(evt);
            }
        });

        ChgPassError.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ChgPassError.setForeground(new java.awt.Color(255, 0, 51));
        ChgPassError.setText("New password must be more than 8 letters !");

        ShowHidePass.setBackground(new java.awt.Color(178, 152, 132));
        ShowHidePass.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        ShowHidePass.setText("Show");
        ShowHidePass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        ShowHidePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowHidePassActionPerformed(evt);
            }
        });

        btnLogout.setBackground(new java.awt.Color(178, 152, 132));
        btnLogout.setFont(new java.awt.Font("Yu Gothic UI", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(46, 36, 28));
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ProfileID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel23))
                                        .addGap(92, 92, 92))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(105, 105, 105)))))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ProfileUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProfileLN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProfileGender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProfileFN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProfileEmail, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ProfileContact, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(161, 161, 161)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel8Layout.createSequentialGroup()
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ShowHidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(ProfileNewPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProfileCurrentPass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ProfileChgPass, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))
                    .addComponent(ChgPassError, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ProfileUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProfileID, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel16)
                                    .addComponent(ProfileFN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(ProfileLN, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProfileGender, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(ProfileEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ProfileContact, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20))
                                .addGap(34, 34, 34)
                                .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(108, 108, 108)
                                        .addComponent(ChgPassError, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ProfileChgPass, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)))
                        .addGap(15, 15, 15))))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(ProfileCurrentPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(7, 7, 7)
                                .addComponent(ShowHidePass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ProfileNewPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.add(jPanel8);
        jPanel8.setBounds(20, 28, 1230, 420);

        jTabbedPane1.addTab("Profile", jPanel3);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 164, 1280, 516);
        jTabbedPane1.getAccessibleContext().setAccessibleName("Profile");

        jPanel5.setBackground(new java.awt.Color(214, 192, 179));
        jPanel5.setLayout(null);

        welcomeMessage.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        welcomeMessage.setForeground(new java.awt.Color(73, 54, 40));
        welcomeMessage.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        welcomeMessage.setText("Admin Dashboard");
        jPanel5.add(welcomeMessage);
        welcomeMessage.setBounds(640, 0, 600, 44);

        jLabel14.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(73, 54, 40));
        jLabel14.setText("Admin Dashboard");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(20, 0, 210, 44);

        getContentPane().add(jPanel5);
        jPanel5.setBounds(0, 120, 1280, 44);

        jPanel2.setBackground(new java.awt.Color(73, 54, 40));
        jPanel2.setLayout(null);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/NexusLogoWhite[1].png"))); // NOI18N
        jPanel2.add(jLabel11);
        jLabel11.setBounds(20, 10, 100, 100);

        Admin_ID.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        Admin_ID.setForeground(new java.awt.Color(214, 192, 179));
        Admin_ID.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        Admin_ID.setText("ADMIN_ID");
        jPanel2.add(Admin_ID);
        Admin_ID.setBounds(980, 0, 260, 120);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1280, 120);

        jPanel6.setBackground(new java.awt.Color(228, 224, 225));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1280, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6);
        jPanel6.setBounds(0, 164, 1280, 40);

        jLabel1.setBackground(new java.awt.Color(214, 192, 179));
        jLabel1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel1.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        password= "";
        ErrorLabels();
        //password generation
        for(int i = 0; i <10; i++){
            password = password.concat(allChars[generator.nextInt(allChars.length)]);
        }
        currentAdmin.Register(user,RegisterFN.getText(), RegisterLN.getText(), RegisterEmail.getText(),
            RegisterContact.getText(), RegisterMale, RegisterFemale, RegisterUID.getText(), RegisterType, password,errorLabels);
        if(user.getUserType() == null){
            return;
         }
        javax.swing.JOptionPane.showMessageDialog(null, "Password : " +password, "Email Sent !", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        currentAdmin.AppendCredentials(user);
        ClearLabels();
        currentAdmin.readLoginCredentials();
        updateTable();
        
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void RegisterContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterContactActionPerformed

    private void RegisterEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterEmailActionPerformed

    private void RegisterFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterFemaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterFemaleActionPerformed

    private void RegisterMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterMaleActionPerformed

    private void RegisterLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterLNActionPerformed

    private void RegisterFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterFNActionPerformed

    private void RegisterTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterTypeActionPerformed
        currentAdmin.readLoginCredentials();        
        if(RegisterType.getSelectedItem().equals("Admin")){
            String usertype = "A";
            RegisterUID.setText(usertype.concat(id.format(Admin.count + 1)));
        }else if(RegisterType.getSelectedItem().equals("Sales Manager (SM)")){
            String usertype = "SM";
            RegisterUID.setText(usertype.concat(id.format(Sales_Manager.count + 1)));
        }else if(RegisterType.getSelectedItem().equals("Purchase Manager (PM)")){
            String usertype = "PM";
            RegisterUID.setText(usertype.concat(id.format(Purchase_Manager.count + 1)));
        }else if(RegisterType.getSelectedItem().equals("Inventory Manager (IM)")){
            String usertype = "IM";
            RegisterUID.setText(usertype.concat(id.format(Inventory_Manager.count + 1)));
        }else if(RegisterType.getSelectedItem().equals("Finance Manager (FM)")){
            String usertype = "FM";
            RegisterUID.setText(usertype.concat(id.format(Finance_Manager.count+1)));

        }

    }//GEN-LAST:event_RegisterTypeActionPerformed

    private void RegisterUIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterUIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegisterUIDActionPerformed

    private void ProfileChgPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfileChgPassActionPerformed
        currentAdmin.readLoginCredentials();       
        currentAdmin.ResetPassword(ProfileCurrentPass.getText(),ProfileNewPass.getText(),ChgPassError, ProfileCurrentPass,ProfileNewPass,ShowHidePass);
        

    }//GEN-LAST:event_ProfileChgPassActionPerformed

    private void ShowHidePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowHidePassActionPerformed
        if(ShowHidePass.isSelected()){
            ProfileNewPass.setEchoChar((char)0);
        }else{
            ProfileNewPass.setEchoChar('\u2022');
        }
    }//GEN-LAST:event_ShowHidePassActionPerformed

    private void SelectUserTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectUserTypeActionPerformed
        updateTable();
    }//GEN-LAST:event_SelectUserTypeActionPerformed

    private void infoFNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoFNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoFNActionPerformed

    private void infoLNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoLNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoLNActionPerformed

    private void infoGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoGenderActionPerformed

    private void infoEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoEmailActionPerformed

    private void infoContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoContactActionPerformed

    private void infoPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infoPasswordActionPerformed

    private void SelectUserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectUserIDActionPerformed
        JTextField allFields[] = {infoFN,infoLN,infoGender,infoEmail,infoContact,infoPassword};
        if(SelectUserID.getSelectedItem() == null){
            return;
        }
        currentAdmin.DisplayUserInfo(SelectUserID.getSelectedItem().toString(),allFields);

        
    }//GEN-LAST:event_SelectUserIDActionPerformed

    private void infoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoEditActionPerformed
        JTextField allFields[] = {infoFN,infoLN,infoGender,infoEmail,infoContact,infoPassword};
        if(infoEdit.isSelected()){
            infoSave.setEnabled(true);
            infoDelete.setEnabled(true);
            for(JTextField field: allFields){
                field.setEditable(true);
                field.setBackground(new Color(214,192,179));
                field.setFocusable(true);
            }
            SelectUserID.setEnabled(false);
            SelectUserType.setEnabled(false);
            jTable1.setEnabled(false);
        }else{
            infoSave.setEnabled(false);
            infoDelete.setEnabled(false);
               for(JTextField field: allFields){
                   field.setEditable(false);
                   field.setBackground(new Color(179,164,155));
                   field.setFocusable(false);
                }
            SelectUserID.setEnabled(true);
            SelectUserType.setEnabled(true);
            jTable1.setEnabled(true);
        }
    }//GEN-LAST:event_infoEditActionPerformed

    private void infoSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoSaveActionPerformed
        JTextField allFields[] = {infoFN,infoLN,infoGender,infoEmail,infoContact,infoPassword};
        if(SelectUserID.getSelectedItem() == null){
             javax.swing.JOptionPane.showMessageDialog(null, "No user ID selected !", "Select User ID", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String ID = SelectUserID.getSelectedItem().toString();
        currentAdmin.updateProfile(infoFN.getText(), infoLN.getText(), infoEmail.getText(), infoContact.getText(), infoGender.getText().toUpperCase(), SelectUserID.getSelectedItem().toString(), infoPassword.getText());        
        updateTable();
        
        SelectUserID.setSelectedItem(ID);
        currentAdmin.DisplayUserInfo(ID,allFields);
        
    }//GEN-LAST:event_infoSaveActionPerformed

    private void infoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infoDeleteActionPerformed
        if(SelectUserID.getSelectedItem() == null){
             javax.swing.JOptionPane.showMessageDialog(null, "No user ID selected !", "Select User ID", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        Object options[] = {"Yes", "No"};
        int choice = javax.swing.JOptionPane.showOptionDialog(null, "This user will be deleted. Confirm?", "Are you sure?" ,javax.swing.JOptionPane.YES_NO_OPTION,javax.swing.JOptionPane.QUESTION_MESSAGE,null,options, "No");
        if(choice == javax.swing.JOptionPane.YES_OPTION){
            currentAdmin.deleteUser(SelectUserID.getSelectedItem().toString());
            updateTable();
            
        }else{
            return;
        }
    }//GEN-LAST:event_infoDeleteActionPerformed

    private void jTable1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MousePressed
        if(jTable1.isEnabled()){
            JTextField allFields[] = {infoFN,infoLN,infoGender,infoEmail,infoContact,infoPassword};
            String ID  = userInfo.getValueAt(jTable1.getSelectedRow(), 1).toString();
//            System.out.println(ID);
            SelectUserID.setSelectedItem(ID);
            currentAdmin.DisplayUserInfo(ID,allFields);
        }else{
            return;
        }

        
    }//GEN-LAST:event_jTable1MousePressed

    private void FMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FMActionPerformed
        this.dispose();  
        new FM_Program(new Finance_Manager(currentAdmin));
    }//GEN-LAST:event_FMActionPerformed

    private void SMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SMActionPerformed
        this.dispose();  
        new SM_Program(new Sales_Manager(currentAdmin));
        
    }//GEN-LAST:event_SMActionPerformed

    private void PMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PMActionPerformed
               this.dispose();  
        new PM_dashboard(new Purchase_Manager(currentAdmin));
    }//GEN-LAST:event_PMActionPerformed

    private void IMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IMActionPerformed
                       this.dispose();  
        new IM_Program(new Inventory_Manager(currentAdmin));
    }//GEN-LAST:event_IMActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here
        this.dispose();
        new LoginUI();

    }//GEN-LAST:event_btnLogoutActionPerformed
    private void ErrorLabels(){
        errorLabels.clear();
        errorLabels.add(FNError);
        errorLabels.add(LNError);
        errorLabels.add(EmailError);
        errorLabels.add(GenderError);
        errorLabels.add(ContactError);
        errorLabels.add(RegisterError);
    }
    
    private void ClearLabels(){
        RegisterUID.setText("");
        RegisterFN.setText("");
        RegisterLN.setText("");
        RegisterEmail.setText("");
        RegisterContact.setText("");
        RegisterGender.clearSelection();
    }
    
    private void ClearErrors(){
        RegisterError.setText("");
        FNError.setText("");
        LNError.setText("");
        EmailError.setText("");
        ContactError.setText("");
        GenderError.setText("");     
        ChgPassError.setText("");
    }
    private void updateTable(){
        if(SelectUserType.getSelectedItem().equals("All")){
            currentAdmin.updateUserInfoTable(userInfo, SelectUserID);
        }else{
            currentAdmin.updateUserInfoTable(userInfo,SelectUserType.getSelectedItem().toString(), SelectUserID);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        // TODO code application logic here
//        new Admin_Program();
        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin_ID;
    private javax.swing.JLabel ChgPassError;
    private javax.swing.JLabel ContactError;
    private javax.swing.JLabel EmailError;
    private javax.swing.JButton FM;
    private javax.swing.JLabel FNError;
    private javax.swing.JLabel GenderError;
    private javax.swing.JButton IM;
    private javax.swing.JLabel LNError;
    private javax.swing.JButton PM;
    private javax.swing.JButton ProfileChgPass;
    private javax.swing.JLabel ProfileContact;
    private javax.swing.JPasswordField ProfileCurrentPass;
    private javax.swing.JLabel ProfileEmail;
    private javax.swing.JLabel ProfileFN;
    private javax.swing.JLabel ProfileGender;
    private javax.swing.JLabel ProfileID;
    private javax.swing.JLabel ProfileLN;
    private javax.swing.JPasswordField ProfileNewPass;
    private javax.swing.JLabel ProfileUserType;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField RegisterContact;
    private javax.swing.JTextField RegisterEmail;
    private javax.swing.JLabel RegisterError;
    private javax.swing.JTextField RegisterFN;
    private javax.swing.JRadioButton RegisterFemale;
    private javax.swing.ButtonGroup RegisterGender;
    private javax.swing.JTextField RegisterLN;
    private javax.swing.JRadioButton RegisterMale;
    private javax.swing.JComboBox<String> RegisterType;
    private javax.swing.JTextField RegisterUID;
    private javax.swing.JButton SM;
    private javax.swing.JComboBox<String> SelectUserID;
    private javax.swing.JComboBox<String> SelectUserType;
    private javax.swing.JToggleButton ShowHidePass;
    private javax.swing.JButton btnLogout;
    private javax.swing.JTextField infoContact;
    private javax.swing.JButton infoDelete;
    private javax.swing.JToggleButton infoEdit;
    private javax.swing.JTextField infoEmail;
    private javax.swing.JTextField infoFN;
    private javax.swing.JTextField infoGender;
    private javax.swing.JTextField infoLN;
    private javax.swing.JTextField infoPassword;
    private javax.swing.JButton infoSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel welcomeMessage;
    // End of variables declaration//GEN-END:variables
}
