/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package assignment_oodj;
import javax.swing.UIManager;
import java.util.Collections;
import com.formdev.flatlaf.FlatIntelliJLaf;
import com.formdev.flatlaf.FlatLaf;
import java.awt.event.KeyEvent;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author User
 */
public class LoginUI extends javax.swing.JFrame {
    User user = new User();
    User currentUser;
    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        LoginError.setText("");
        user.readLoginCredentials();        
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        //readfile 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        LoginID = new javax.swing.JTextField();
        LoginPass = new javax.swing.JPasswordField();
        LoginButton = new javax.swing.JButton();
        LoginError = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login ");
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(73, 54, 40));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(420, 380));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(171, 136, 109));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Sign In");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(171, 136, 109));
        jLabel3.setText("User ID");

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(171, 136, 109));
        jLabel4.setText("Password");

        LoginID.setBackground(new java.awt.Color(214, 192, 179));
        LoginID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginID.setForeground(new java.awt.Color(83, 60, 43));
        LoginID.setToolTipText("User ID");
        LoginID.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        LoginID.setSelectionColor(new java.awt.Color(178, 152, 132));
        LoginID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginIDActionPerformed(evt);
            }
        });

        LoginPass.setBackground(new java.awt.Color(214, 192, 179));
        LoginPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        LoginPass.setForeground(new java.awt.Color(83, 60, 43));
        LoginPass.setToolTipText("Password");
        LoginPass.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        LoginPass.setMinimumSize(new java.awt.Dimension(64, 26));
        LoginPass.setPreferredSize(new java.awt.Dimension(64, 26));
        LoginPass.setSelectionColor(new java.awt.Color(178, 152, 132));
        LoginPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginPassActionPerformed(evt);
            }
        });
        LoginPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                LoginPassKeyPressed(evt);
            }
        });

        LoginButton.setBackground(new java.awt.Color(178, 152, 132));
        LoginButton.setFont(new java.awt.Font("Yu Gothic UI", 1, 20)); // NOI18N
        LoginButton.setForeground(new java.awt.Color(46, 36, 28));
        LoginButton.setText("Log In");
        LoginButton.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 2, 3, 2, new java.awt.Color(53, 41, 33)));
        LoginButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });

        LoginError.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        LoginError.setForeground(new java.awt.Color(255, 0, 51));
        LoginError.setText("Credentials not found !! Try Again !!!");

        jSeparator2.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator2.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator3.setBackground(new java.awt.Color(171, 136, 109));
        jSeparator3.setForeground(new java.awt.Color(171, 136, 109));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LoginID)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(LoginError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(1, 1, 1)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LoginID, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LoginPass, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jSeparator2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LoginError, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(LoginButton, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(38, 38, 38))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(480, 150, 360, 380);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg.jpg"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(1280, 720));
        jLabel2.setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1290, 730);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void LoginIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginIDActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        currentUser = user.Login(LoginID.getText(), LoginPass.getText(), LoginError);        
        if(currentUser == null){
            return;
        }
        System.out.println(currentUser.getClass());
        this.dispose();
        currentUser.Start();

    }//GEN-LAST:event_LoginButtonActionPerformed

    private void LoginPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginPassActionPerformed

    }//GEN-LAST:event_LoginPassActionPerformed

    private void LoginPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_LoginPassKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            currentUser = user.Login(LoginID.getText(), LoginPass.getText(), LoginError);        
            if(currentUser == null){
                return;
            }
            System.out.println(currentUser.getClass());
            this.dispose();
            currentUser.Start();
            }
    }//GEN-LAST:event_LoginPassKeyPressed


    /**
     * @param args the command line arguments
     */

    public static void main(String[] args) {
        // TODO code application logic here
        
//        try {
//        UIManager.setLookAndFeel(new FlatIntelliJLaf());
//        FlatLaf.setGlobalExtraDefaults( Collections.singletonMap( "@accentColor", "#AB886D" ));
//        FlatIntelliJLaf.setup();
//        LoginUI login = new LoginUI();
//        /* Create and display the form */
//    } catch (UnsupportedLookAndFeelException ex) {
////        Logger.getLogger(SM_Program.class.getName()).log(Level.SEVERE, null, ex);
//        System.out.println("Please install flatlaf for a better experience!");
//        }
//        
//        
//        
        
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginError;
    private javax.swing.JTextField LoginID;
    private javax.swing.JPasswordField LoginPass;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
